name = "PredatorPreyTutorial"
uuid = "57f5783d-547e-4ee8-be84-f0d6b205fe81"
authors = ["Rajith Vidanaarachchi"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
